services:
  nvoptee:
    container_name: nvoptee
    #platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/optee
